### ISSUE TITLE
[BUG] Can't run in linux

### ISSUE THREAD

**Issue by huskyy8y8** [Sxvxgee/UnlimitedGPT#32]
root@instance-20230731-0438:~/svbot# python3 test.py
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    api = ChatGPT(key)
  File "/usr/local/lib/python3.8/dist-packages/UnlimitedGPT/UnlimitedGPT.py", line 76, in __init__
    self._init_browser()
  File "/usr/local/lib/python3.8/dist-packages/UnlimitedGPT/UnlimitedGPT.py", line 187, in _init_browser
    self._ensure_cf()
  File "/usr/local/lib/python3.8/dist-packages/UnlimitedGPT/UnlimitedGPT.py", line 277, in _ensure_cf
    response = self.driver.find_element(By.TAG_NAME, "pre").text
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 831, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"tag name","selector":"pre"}
  (Session info: chrome=115.0.5790.170)
Stacktrace:
#0 0x5611a106c4e3 <unknown>
#1 0x5611a0d9bc76 <unknown>
#2 0x5611a0dd7c96 <unknown>
#3 0x5611a0dd7dc1 <unknown>
#4 0x5611a0e117f4 <unknown>
#5 0x5611a0df703d <unknown>
#6 0x5611a0e0f30e <unknown>
#7 0x5611a0df6de3 <unknown>
#8 0x5611a0dcc2dd <unknown>
#9 0x5611a0dcd34e <unknown>
#10 0x5611a102c3e4 <unknown>
#11 0x5611a10303d7 <unknown>
#12 0x5611a103ab20 <unknown>
#13 0x5611a1031023 <unknown>
#14 0x5611a0fff1aa <unknown>
#15 0x5611a10556b8 <unknown>
#16 0x5611a1055847 <unknown>
#17 0x5611a1065243 <unknown>
#18 0x7f89708c6609 start_thread

<img width="372" alt="image" src="https://github.com/Sxvxgee/UnlimitedGPT/assets/69740916/cdb4ef29-5acf-4671-940f-aecb51cb69a3">

**Comment by Sxvxgee** [comment]
Are you sure you're using the latest version of this library? I'm running the same code as you and its working well

**Comment by huskyy8y8** [comment]
Yes follow the tutorial and run the latest version

**Comment by Sxvxgee** [comment]
show me a screenshot of the chatgpt website when you open it
