### ISSUE TITLE
ERROR CHROME VERSION

### ISSUE THREAD

**Issue by webmestudio** [Sxvxgee/UnlimitedGPT#44]
C:\Users\NONAME\Downloads\unlimitedgpt>python main.py
Traceback (most recent call last):
  File "C:\Users\NONAME\Downloads\unlimitedgpt\main.py", line 6, in <module>
    api = ChatGPT(
  File "C:\Users\NONAME\Downloads\unlimitedgpt\UnlimitedGPT\UnlimitedGPT.py", line 77, in __init__
    self._init_browser()
  File "C:\Users\NONAME\Downloads\unlimitedgpt\UnlimitedGPT\UnlimitedGPT.py", line 160, in _init_browser
    self.driver = ChatGPTDriver(options=options, headless=self._headless)
  File "C:\Users\NONAME\Downloads\unlimitedgpt\UnlimitedGPT\internal\driver.py", line 16, in __init__
    super().__init__(options=options, headless=headless, desired_capabilities=caps)
  File "C:\Users\NONAME\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\undetected_chromedriver\__init__.py", line 441, in __init__
    super(Chrome, self).__init__(
  File "C:\Users\NONAME\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\chrome\webdriver.py", line 84, in __init__
    super().__init__(
  File "C:\Users\NONAME\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\chromium\webdriver.py", line 104, in __init__
    super().__init__(
  File "C:\Users\NONAME\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 286, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\NONAME\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\undetected_chromedriver\__init__.py", line 704, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "C:\Users\NONAME\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 378, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\NONAME\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "C:\Users\NONAME\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:50446
from session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 117.0.5938.132
Stacktrace:
Backtrace:
        GetHandleVerifier [0x0040A813+48355]
        (No symbol) [0x0039C4B1]
        (No symbol) [0x002A5358]
        (No symbol) [0x002C61AC]
        (No symbol) [0x002C06B4]
        (No symbol) [0x002C0491]
        (No symbol) [0x002F0C55]
        (No symbol) [0x002F093C]
        (No symbol) [0x002EA536]
        (No symbol) [0x002C82DC]
        (No symbol) [0x002C93DD]
        GetHandleVerifier [0x0066AABD+2539405]
        GetHandleVerifier [0x006AA78F+2800735]
        GetHandleVerifier [0x006A456C+2775612]
        GetHandleVerifier [0x004951E0+616112]
        (No symbol) [0x003A5F8C]
        (No symbol) [0x003A2328]
        (No symbol) [0x003A240B]
        (No symbol) [0x00394FF7]
        BaseThreadInitThunk [0x75F66739+25]
        RtlGetFullPathName_UEx [0x777A8AFF+1215]
        RtlGetFullPathName_UEx [0x777A8ACD+1165]

**Comment by JiyangZhang** [comment]
same problem here

**Comment by alexlaverty** [comment]
I'm getting the same error, I think either need to upgrade the ChromeDriver or downgrade the Chrome browser to version 114 

This version of ChromeDriver only supports **Chrome version 114**
Current browser **version is 117**.0.5938.132

**Comment by RylonW** [comment]
I met with the same question, but  I could excuate the browser successfully with:
`driver = webdriver.Chrome(executable_path='/usr/bin/google-chrome')`
and I tried to add parameters for init.py file:
`        super().__init__(options=options, headless=headless, desired_capabilities=caps, driver_executable_path='/usr/bin/google-chrome')`
but it failed with "PermissionError: [Errno 13] Permission denied: '/usr/bin/google-chrome'"
I need more help!! I think 114 chromedriver version is too old to adapt the environment now. The latest chrome version is 117. Hope to hear more replies!

**Comment by pik-a-c-h-u** [comment]
> I met with the same question, but I could excuate the browser successfully with: `driver = webdriver.Chrome(executable_path='/usr/bin/google-chrome')` and I tried to add parameters for init.py file: ` super().__init__(options=options, headless=headless, desired_capabilities=caps, driver_executable_path='/usr/bin/google-chrome')` but it failed with "PermissionError: [Errno 13] Permission denied: '/usr/bin/google-chrome'" I need more help!! I think 114 chromedriver version is too old to adapt the environment now. The latest chrome version is 117. Hope to hear more replies!

download latest chrome driver and give its path instead , might just work

**Comment by pik-a-c-h-u** [comment]
First got to [https://googlechromelabs.github.io/chrome-for-testing/](url) and download the latest chrome driver
then open driver.py (location :  /UnlimitedGPT/internal/driver.py)
then change line 16 to `super().__init__(options=options, headless=headless, desired_capabilities=caps, driver_executable_path="C:\chrome\chromedriver-win64\chromedriver.exe")`
here give the path of the chrome driver that u downloaded 
save it and run it , should work fine

**Comment by pik-a-c-h-u** [comment]
> I met with the same question, but I could excuate the browser successfully with: `driver = webdriver.Chrome(executable_path='/usr/bin/google-chrome')` and I tried to add parameters for init.py file: ` super().__init__(options=options, headless=headless, desired_capabilities=caps, driver_executable_path='/usr/bin/google-chrome')` but it failed with "PermissionError: [Errno 13] Permission denied: '/usr/bin/google-chrome'" I need more help!! I think 114 chromedriver version is too old to adapt the environment now. The latest chrome version is 117. Hope to hear more replies!

download the latest chrome driver form [https://googlechromelabs.github.io/chrome-for-testing/](https://github.com/Sxvxgee/UnlimitedGPT/issues/url) and use that as the driver_executable_path

**Comment by dsldsl** [comment]
Trying to work through this still if anyone's active and had an ideas
